/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "deep-navy": "#0B3D6E",
        "primary": "#00274c",
        "primary-container": "#0b3d6e",
        "on-primary": "#ffffff",
        "on-primary-container": "#82a9e0",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#a4c9ff",
        "inverse-primary": "#a4c9ff",
        "secondary": "#6c5e00",
        "secondary-container": "#fee000",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#716300",
        "secondary-fixed": "#ffe330",
        "secondary-fixed-dim": "#e1c700",
        "safety-yellow": "#FFE100",
        "soft-canary": "#FEFBD8",
        "sky-tint": "#E5EAF3",
        "tertiary": "#22272e",
        "tertiary-container": "#373d44",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#a2a7b0",
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#386093",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#43474f",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "outline": "#737780",
        "outline-variant": "#c3c6d0",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "manrope": ["Manrope", "sans-serif"],
        "opensans": ["Open Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      spacing: {
        "stack-lg": "48px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "gutter": "16px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "container-max": "1200px",
        "base": "8px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};
